# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Footer
title: Yangcheng Gu
author: Yangcheng Gu
email: yangcheg@andrew.cmu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Second-year MSIN student at CMU. This is my personal website where I share notes on programming and algorithms.

# Links
cv_link: ./assets/files/Resume - Yangcheng Gu.pdf
github_username:  ferv3455
linkedin_username: yangcheng-gu

# URL settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ferv3455.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/ferv.png

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc
  - jekyll-sitemap

# Header pages
header_pages:
  - notes.md
  - leetcode.md

# TOC settings
toc:
  min_level: 2
  max_level: 3

# Collections
collections:
  personal:
    output: true
  cpp_primer:
    output: true
  cracking_the_coding_interview:
    output: true
  cs_fundamentals:
    output: true
  effective_python:
    output: true
  fluent_python:
    output: true
  learning_go:
    output: true
  leetcode_problems:
    output: true
  leetcode_notes:
    output: true
  miscellaneous:
    output: true
  random_notes_of_coding:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
