# Basic Information 
title: Yangcheng Gu
position: Graduate Student (Master's)
affiliation: Information Networking Institute, Carnegie Mellon University
affiliation_link: https://www.cmu.edu/ini/
email: yangcheg@andrew.cmu.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Yangcheng Gu
description: Self-introduction and academic background of Yangcheng Gu.
# canonical: https://minimal-light-theme.yliu.me/

# Links 
# If you don't need one of them, you may delete the corresponding line.
# google_scholar: https://scholar.google.com/
cv_link: assets/files/Resume - Yangcheng Gu.pdf
github_link: https://github.com/ferv3455
linkedin: https://www.linkedin.com/in/yangcheng-gu/
# twitter: https://twitter.com/GUferv3455

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/ferv.png
favicon_dark: ./assets/img/ferv.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: false

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
# font: "Serif"
font: "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# Code highlighting
markdown: CommonMarkGhPages
highlighter: rouge

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
